POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "Vinicius",
  "email": "vinigodoy@gmail.com",
  "password": "password"
}

### Get the first user
GET localhost:8080/api/users
